version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.1
    steps:
      - checkout
      - run: pip install -r requirements.txt
  test:
    docker:
      - image: circleci/python:3.5.1
    steps:
      - checkout
      - run: pytest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test